### ISSUE TITLE
配完环境后好像运行不了有bug

### ISSUE THREAD

**Issue by SHIMURA0** [TebooNok/HiQA#1]
当我运行app_streamlit.py 这个文件时，会出现这个错误
Traceback (most recent call last):
  File "/Users/shimura/Pycharm Projects/pythonProject/HiQA/app_streamlit.py", line 3, in <module>
    from service.knowledge_client import *
  File "/Users/shimura/Pycharm Projects/pythonProject/HiQA/service/knowledge_client.py", line 583, in <module>
    init()
  File "/Users/shimura/Pycharm Projects/pythonProject/HiQA/service/knowledge_client.py", line 498, in init
    for filename in os.listdir('datasets/4_1_TI_origin/embeddings'):
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/4_1_TI_origin/embeddings'
我检查了datasets/4_1_TI_origin这个文件夹确实没有这个embeddings文件；
然后当我运行PYTHONUNBUFFERED=1 nohup streamlit run app_streamlit.py --server.port 8080 --server.address 0.0.0.0 > logs/run.log 2>&1 &，会出现这个错误
zsh: no such file or directory: logs/run.log
作者能不能帮忙看看，提前谢谢了

**Comment by TebooNok** [comment]
你好，
1. 我更新了代码，您可以pull一下。knowledge_client误加载了几个测试数据集。
2. 运行时的错误可能是您需要手动建立logs目录。
