### ISSUE TITLE
sqlite3.OperationalError: no such table: collections

### ISSUE THREAD

**Issue by ljcsweet** [TebooNok/HiQA#11]
Collection chipanalog1985 created
Collection analog_book3056 created
Collection financial6127 created
Collection texas5875 created
enemy doc size: 1638
load data successful   请问是否还有别的步骤来创建表，还是自动创建的，在哪里修改会纠正此错误

**Comment by TebooNok** [comment]
你好，这个程序和sqlite关联的地方是whoosh创建的索引，
程序会在启动时加载一次指定的数据集，但这一步不会创建新表。
我怀疑你遇到的错误是在搜索时，程序会对搜索结果进行重拍，此时会在临时目录创建whoosh索引。
具体定位需要发一下Exception Trace log，看下异常抛出的位置

**Comment by ljcsweet** [comment]
非常感谢您百忙之中的回复，我对你们的项目非常感兴趣！，我的运行平台是WIN11，pycharm编辑器。以下是完整的报错信息
C:\Users\ljcsweet\.conda\envs\hiqa\python.exe -X pycache_prefix=C:\Users\ljcsweet\AppData\Local\JetBrains\PyCharm2024.1\cpython-cache "D:/software/PyCharm 2024.1.1/plugins/python/helpers/pydev/pydevd.py" --multiprocess --client 127.0.0.1 --port 52502 --file C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\streamlit run app_streamlit.py --server.address 0.0.0.0 --server.port 8080 
Connected to pydev debugger (build 241.15989.155)


  You can now view your Streamlit app in your browser.


  URL: http://0.0.0.0:8080


init project
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ljcsweet\AppData\Local\Temp\jieba.cache
Loading model cost 0.313 seconds.
Prefix dict has been built successfully.
Collection chipanalog created
Collection analog_book created
Collection financial created
Collection texas created
enemy doc size: 1638
load data successful
2024-11-25 22:30:00.592 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
begin...
after embedding 3.3518192768096924
2024-11-25 22:30:14.763 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "E:\code\HiQA-main\app_streamlit.py", line 72, in <module>
    knowledge = get_knowledge(user_input, max_tokens, dataset, begin, only_vec=only_vec, verbose=True)
  File "E:\code\HiQA-main\service\knowledge_client.py", line 39, in get_knowledge
    knowledge = retrieve_knowledge(question, question_embd, max_token, dataset, begin, only_vec=only_vec, verbose=verbose)
  File "E:\code\HiQA-main\service\knowledge_client.py", line 146, in retrieve_knowledge
    results = collection.query(
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\api\models\Collection.py", line 221, in query
    query_results = self._client._query(
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 150, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\tenacity\__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\tenacity\__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\tenacity\__init__.py", line 376, in iter
    result = action(retry_state)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\tenacity\__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\api\segment.py", line 103, in wrapper
    return self._rate_limit_enforcer.rate_limit(func)(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\rate_limit\simple_rate_limit\__init__.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\api\segment.py", line 789, in _query
    coll = self._get_collection(collection_id)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 150, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\api\segment.py", line 890, in _get_collection
    collections = self._sysdb.get_collections(id=collection_id)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 150, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\ljcsweet\.conda\envs\hiqa\lib\site-packages\chromadb\db\mixins\sysdb.py", line 446, in get_collections
    rows = cur.execute(sql, params).fetchall()
sqlite3.OperationalError: no such table: collections
  Stopping...


Process finished with exit code 0













在 2024-11-25 17:16:33，"Xinyue Chen" ***@***.***> 写道：

你好，这个程序和sqlite关联的地方是whoosh创建的索引，
程序会在启动时加载一次指定的数据集，但这一步不会创建新表。
我怀疑你遇到的错误是在搜索时，程序会对搜索结果进行重拍，此时会在临时目录创建whoosh索引。
具体定位需要发一下Exception Trace log，看下异常抛出的位置

**Comment by TebooNok** [comment]
您好，不客气。
- 可能性1（可能性不大）：
请阅读本项目的readme中关于数据集的部分，本项目的数据集移动到了另一个project下[MasQA](https://github.com/TebooNok/MasQA)，以免fork/clone困难。
您检查一下是否下载了数据集中的内容，并放在```/datasets/```目录下，例如```/datasets/1_Chipanalog/```
- 可能性2：
我没有在requirements里标准准确的版本，从报错上看，这属于Chroma内部的错误，chroma的client是用默认配置创建的。可以考虑将chroma回退到0.5.0的版本再次尝试. ```pip install chromadb==0.5.0```

**Comment by ljcsweet** [comment]
非常感谢您的回复，根据您的建议，此问题已经完美解决，祝您生活愉快，事业有成！











在 2024-11-25 23:06:39，"Xinyue Chen" ***@***.***> 写道：

您好，不客气。

可能性1（可能性不大）：
请阅读本项目的readme中关于数据集的部分，本项目的数据集移动到了另一个project下MasQA，以免fork/clone困难。
您检查一下是否下载了数据集中的内容，并放在/datasets/目录下，例如/datasets/1_Chipanalog/
可能性2：
我没有在requirements里标准准确的版本，从报错上看，这属于Chroma内部的错误，chroma的client是用默认配置创建的。可以考虑将chroma回退到0.5.0的版本再次尝试. pip install chromadb==0.5.0
